### ISSUE TITLE
在运行时增加对执行对象字段的校验

### ISSUE THREAD

**Issue by weideguo** [weideguo/solvestack#25]

**Comment by weideguo** [comment]
``` yaml
target:
  -
    field: db_from
    comment: 迁移的源实例
    constrict: server_*mysql* 
    sub:
      -
        field: host
        comment: 迁移的源实例所在的主机
        constrict: host_*
        sub:
          -
            field: ip
            comment: 迁移的源实例所在的主机的ip
      -
        field: port
        comment: 迁移的源实例端口号
    
  -
    field: db_to
    comment: 迁移的目标实例
    constrict: server_*mysql* 
```
